[project]
name = "pirate-agent-a2a"
version = "0.1.0"
description = "Pirate Agent (A2A-compliant)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "a2a-server>=0.1.0",
    "google-adk>=0.2.0",
    "litellm>=1.67.0",
    "python-dotenv>=1.1.0",
]
